<?php
return array(
    'administrador' => array(
        'Accesorios' => 'on',
        'Clientes' => 'on',
        'Detalle Facturas' => 'on',
        'Detalle Reparaciones' => 'on',
        'Dispositivos' => 'on',
        'Empleados' => 'on',
        'Facturas' => 'on',
        'Notificaciones' => 'on',
        'Pagos' => 'on',
        'Pedidos de Reparación' => 'on',
        'Piezas y Componentes' => 'on',
        'Proveedores' => 'on',
        'Recibos' => 'on',
        'Reparaciones' => 'on',
        'Roles' => 'on',
        'Técnicos' => 'on',
        'Tickets' => 'on',
        'Usuarios' => 'on',
        'Ventas Accesorios' => 'on',
    ),
    'tecnico' => array(
        'Accesorios' => 'on',
        'Clientes' => 'on',
        'Detalle Reparaciones' => 'on',
        'Dispositivos' => 'on',
        'Notificaciones' => 'on',
        'Pedidos de Reparación' => 'on',
        'Reparaciones' => 'on',
    ),
    'supervisor' => array(
        'Clientes' => 'on',
        'Notificaciones' => 'on',
        'Pedidos de Reparación' => 'on',
    ),
);
